### ISSUE TITLE
Invalid puzzle not recognized as invalid upon loading.

### ISSUE THREAD

**Issue by danieh65** [akiekintveld/Sudoku#3]
**Requirement 2-c**: The UI will immediately display the state of the puzzle: normal, invalid, and solved.  If the puzzle is invalid, the entire UI should be locked.  The invalid squares should be marked red.
**Expected**: Puzzle is locked and invalid squares are marked red.
**Observed**: Puzzle is loaded as if it is valid.
**Test Data**: `InvalidPuzzle.txt`
**Repro steps**:
1. Launch application.
2. Attempt to load either of the above files, or another file with an invalid puzzle.

**Comment by akiekintveld** [comment]
Fixed in dd93a8aacbcdc9b9d0e46f76589e2c47496d0630 ✅
